services:
  mcp-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dowhistle-mcp-gateway-dev
    image: dowhistle-mcp-gateway:dev
    volumes:
      - .:/app
      - /app/node_modules   # ensures container has its own node_modules, not overwritten
    ports:
      - "${PORT:-3001}:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      ALLOWED_ORIGINS: "*"
